### ISSUE TITLE
Extend description in Readme file

### ISSUE THREAD

**Issue by JoeyStk** [JoeyStk/CV_Generator#9]
The description in the readme file is still the bare minimum. I think we should extend the readme by some additional information:

- Intro: What is this project and what was the motivation for it? Is this project online already?
- Collaboration: Do we want to have external contributions for it or not?
- Installation process: What do you need to install the project?
- User management: Which roles exist and what are the logins for the dummy user?

**Comment by amikable-tech** [comment]
Thank you for this issue Johannes.
I can do like a draft docx of what the Readme file should look like.
I have seen some repo where they said run something like 

- git clone <repo-url>
- pip install -r requirements.txt 
- that means we need to write out all modules that we used in a txt file.

which means that essentially we will be updating the readme periodically right?
